version: '3.9'

services:
  # api:
  #   image: itf-clubmanagement-api
  #   build: ./itf-club-management
  #   ports:
  #     - "5000:80"
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    environment:
      KC_HTTP_ENABLED: 'true'
      KC_HTTP_PORT: 8080
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: none
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - ./config/:/opt/keycloak/data/import/
    command:
      - start-dev 
      - --import-realm

volumes:
  postgres_data:
